name: Build

on: [push, pull_request]

jobs:
  docs:
    uses: DFHack/dfhack/.github/workflows/build-linux.yml
    with:
      dfhack_ref: develop
      scripts_ref: ${{ github.ref }}
      artifact-name: docs
      platform-files: false
      common-files: false
      docs: true
    secrets: inherit

  lint:
    uses: DFHack/dfhack/.github/workflows/lint.yml@develop
    with:
      dfhack_ref: develop
      scripts_ref: ${{ github.ref }}
    secrets: inherit
